### ISSUE TITLE
This library is *not* obsolete!

### ISSUE THREAD

**Issue by drvink** [yuutayamada/flycheck-tip#14]
There is no need to deprecate this library just because `flycheck-pos-tip` exists! This one is actually better than `flycheck-pos-tip`: because it uses `popup`, it works on both terminals and `window-system` Emacs.

**Comment by yuutayamada** [comment]
Well thanks for the comment and sorry for very late reply. Because of re-fafactored flymake from Emacs 26, I found usefulness of this package, so yes, I'll keep maintain this package:)
(FYI: https://lists.gnu.org/archive/html/emacs-devel/2017-09/msg00953.html)
