### ISSUE TITLE
Error: (void-function flycheck-tip-display-current-line-error-message)

### ISSUE THREAD

**Issue by robert-zaremba** [yuutayamada/flycheck-tip#8]
When activating verbose output:

    (flycheck-tip-use-timer 'verbose)

I'm constantly having the following message in my echo area (while hovering on a line with error):

    Error: (void-function flycheck-tip-display-current-line-error-message)

**Comment by yuutayamada** [comment]
Sorry, wrongly I had deleted that function. Now I've added that function.
Could you update this package?

**Comment by robert-zaremba** [comment]
thanks
