### ISSUE TITLE
flycheck-tip is not on MELPA Stable

### ISSUE THREAD

**Issue by rycee** [yuutayamada/flycheck-tip#9]
It would be very nice to have a stable version on [MELPA Stable](http://stable.melpa.org/). The process is [quite simple](https://github.com/milkypostman/melpa#stable-packages), basically making a GIT tag.

**Comment by yuutayamada** [comment]
Thanks for good suggestion!
I added the version tag this package.

**Comment by rycee** [comment]
Wonderful! Many thanks.
